- name: sample variable
  hosts: all
  #vars:
   # url: google.com
  vars_files:
    - sample-variable.yml
  tasks:
    - name: print url
      ansible.builtin.debug:
        msg: "This is my url {{url}} and  url1 - {{url1}}"
